from colorama import Fore

DROP_COLOUR = Fore.LIGHTGREEN_EX
DAMAGE_COLOUR = Fore.LIGHTYELLOW_EX
SPELL_COLOUR = Fore.LIGHTMAGENTA_EX
SPELL_COLOUR_HEAL = Fore.LIGHTGREEN_EX
ABILITIES_COLOUR = Fore.LIGHTYELLOW_EX
RESET = Fore.RESET